server:
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://220.123.184.52:3306/rrps?autoReconnect=true&useSSL=false
    username: root
    password: iot.admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  logging:
    file:
      name: ./logs/spring.log
      max-history: 30
      max-size: 10MB
    level:
      root: info
      org.apache.http: info
    pattern:
      console: "%d{HH:mm:ss.SSS} [%t] %-5level [%logger{36}:%L] - %msg%n"
      file: "%d [%t] %5p [%c{1.}:%L] %m%n"

mybatis:
  type-aliases-package: com.assembble.gc.dto
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mapper/*.xml
